# Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30

# Spring settings
spring:
  thymeleaf:
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://wangrui/~/pinecone
    username: pinecone
    password: pinecone

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
